"""
Django settings for urban_app project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APPEND_SLASH = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ef2wh5qa)_6fp^1ev9o17kd+aok&x8us%k0wv(xyl#)og#ax6n"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "core_app",
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'dynamic': True,
    'menus': [
        {
            'app': 'auth',
            'name': 'Authority authentication',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': 'Users',
                    'icon': 'fa fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': 'Group',
                    'icon': 'fa fa-th-list',
                    'url': 'auth/group/'
                }
            ]
        },

        {
            'name': 'Map',
            'icon': 'fa-solid fa-map-pin',
            'url': '/core_app/home'
        },

        {
            'name': 'Report',
            'icon': 'fa-solid fa-upload',
            'url': '/core_app/report'
        },
        {
            'name': 'Incident',
            'icon': 'fa-solid fa-display',
            'url': '/core_app/getIncident'
        },

    ]
}

SIMPLEUI_LOGO = 'https://th.bing.com/th/id/R.7ac09a9d90b9c77701b10e7ed15e4469?rik=Wsyt7dtx8aZm6Q&riu=http%3a%2f%2fimg95.699pic.com%2felement%2f40020%2f2495.png_860.png&ehk=pZZbBYppQwMOTeiMVC5Rgq5yadtfl3XwEZ7qeHsrwuc%3d&risl=&pid=ImgRaw&r=0'

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "urban_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "urban_app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database
DATABASES = {
    'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'city_disaster_response',
            'USER': 'root_dev',
            'PASSWORD': 'PasswordRoot010',
            'HOST': 'disasterrecoveryapplication.criuoqqmqhlh.eu-north-1.rds.amazonaws.com',
            'PORT': '3306'
        },
    'test': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'test_city_disaster_response',
            'USER': 'root',
            'PASSWORD': 'PasswordRoot010',
            'HOST': 'disasterrecoveryapplication.criuoqqmqhlh.eu-north-1.rds.amazonaws.com',
            'PORT': '3306'
        }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = '/core_app/static/core_app/'
# ...

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

