# Generated by Django 4.2.6 on 2024-03-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('incident', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
