# Generated by Django 4.2.6 on 2024-02-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='incident_images/')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='incident_images/')),
                ('incident_type', models.CharField(max_length=255, null=True)),
                ('occur_time', models.DateTimeField()),
                ('status', models.CharField(max_length=255, null=True)),
                ('traffic_status', models.CharField(max_length=255, null=True)),
                ('scale_impact', models.CharField(max_length=255, null=True)),
                ('extrainfo', models.JSONField()),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
